# Generated by Django 5.2.4 on 2025-07-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='<function uuid4 at 0x72d656bcba30>', max_length=100, unique=True),
        ),
    ]
