# Generated by Django 5.2.4 on 2025-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='<function uuid4 at 0x72617f85bac0>', max_length=100, unique=True),
        ),
    ]
